{% set name = "pysbol2" %}
{% set version = "v1.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/SynBioDex/pySBOL2/archive/{{ version }}.tar.gz
  sha256: 7adf62fb7edb204b27893ecaedc98bac6269c6734a5fb1717fd98d694b277391

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install -vv .

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - deprecated
    - lxml
    - packaging >=20.0
    - python-dateutil
    - rdflib >=5.0
    - requests
    - urllib3
    - openjdk

test:
  source_files:
    - test
    - examples
  imports:
    - sbol2
  commands:
    - pip check
    - git clone --recurse-submodules https://github.com/SynBioDex/pySBOL2.git && cp -r pySBOL2/test/SBOLTestSuite test/.
    - python -m unittest discover -s test
  requires:
    - pip
    - git

about:
  home: https://github.com/SynBioDex/pySBOL2/
  summary: Pure Python implementation of SBOL 2 standard
  license: Apache-2.0
  license_file: LICENSE.txt
  description: |
    pySBOL2 is a pure Python implementation of the SBOL 2.3.0
    standard Synthetic Biology Open Language (SBOL) - an open
    standard for the representation of in silico biological
    designs. It draws from libSBOL and pySBOL.
  doc_url: https://pysbol.readthedocs.io/en/stable/

extra:
  recipe-maintainers:
    - tduigou
